# Generated by Django 4.1.3 on 2022-11-10 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('favorites', '0003_favoritecategory_favorite_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritecategory',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_category_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
