# Generated by Django 4.1.3 on 2022-11-14 06:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
