# Generated by Django 4.1.3 on 2022-11-12 17:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_action',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
