# Generated by Django 4.1.3 on 2022-11-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hide_status',
            field=models.BooleanField(default=False),
        ),
    ]
