# Generated by Django 4.1.3 on 2022-11-18 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_rename_owner_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='update_at',
        ),
    ]
