# Generated by Django 4.1.3 on 2022-11-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_postslike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postslike',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
