# Generated by Django 4.1.3 on 2022-11-21 06:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0008_userreadtime_alter_post_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_read',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserReadTime',
        ),
    ]
