# Generated by Django 4.1.3 on 2022-11-21 06:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_userreadtime_alter_post_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreadtime',
            name='read_time',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
    ]
