# Generated by Django 4.1.3 on 2022-11-21 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_alter_userreadtime_read_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_read',
        ),
        migrations.AddField(
            model_name='userreadtime',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post_is_read', to='post.post'),
            preserve_default=False,
        ),
    ]
