# Generated by Django 4.1.3 on 2022-11-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follower', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='is_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
