# Generated by Django 4.1.3 on 2022-11-18 09:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_groupchatsettings_groupmessages_groupmembers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessages',
            name='is_read',
        ),
        migrations.AddField(
            model_name='groupmessages',
            name='is_read',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
